apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-config
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data:
  application.conf: |
    # Injected from the Kubernetes Secret via env var
    play.http.secret.key = ${?PLAY_SECRET}

    db.janusgraph {
      storage {
        backend = cql
        hostname = [ {{ .Values.cassandra.host | quote }} ]
        port = {{ .Values.cassandra.port }}
        cql {
          cluster-name = {{ .Values.cassandra.clusterName }}
          keyspace = {{ .Values.cassandra.keyspace }}
          local-datacenter = {{ .Values.cassandra.localDatacenter }}
          replication-factor = {{ .Values.cassandra.replicationFactor }}
        }
      }
      index.search {
      {{- if eq .Values.index.backend "elasticsearch" }}
        backend = elasticsearch
        hostname = [ {{- range $i, $h := .Values.index.elasticsearch.hosts }}{{ if $i }}, {{ end }}{{ $h | quote }}{{- end }} ]
        index-name = {{ .Values.index.elasticsearch.indexName }}
      {{- else }}
        backend = lucene
        directory = {{ .Values.index.luceneDirectory | quote }}
      {{- end }}
      }
    }

    storage {
      provider = localfs
      localfs.location = {{ .Values.fileStorage.location | quote }}
    }

    play.http.parser.maxDiskBuffer = 1GB
    play.http.parser.maxMemoryBuffer = 10M
