apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"      # database first
spec:
  project: default
  source:
    repoURL: https://github.com/santoshdandi/gitops.git   # <-- change
    targetRevision: main
    path: charts/cassandra
    helm:
      releaseName: cassandra
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: thehive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
