apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thehive-mcp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"      # after cassandra (0) and thehive (1)
spec:
  project: default
  source:
    repoURL: https://github.com/santoshdandi/gitops.git   # change
    targetRevision: main
    path: manifests/thehive-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: thehive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true